### ISSUE TITLE
新版直播间页面，功能失效了。。。

### ISSUE THREAD

**Issue by kkocdko** [MoeHero/BilibiliHelper#10]
### 问题反馈
新版直播间页面，功能失效
期盼着大大尽快更新呢。。。

### 环境信息
- 操作系统 (Windows10 16299):
- 浏览器版本 (chrome63 金丝雀):
- 插件版本 (哎呀就是最新的咯):

**Comment by elfgzp** [comment]
不能用啦～大大加油～催更

**Comment by MoeHero** [comment]
新版制作中
