### ISSUE TITLE
显示未绑定手机

### ISSUE THREAD

**Issue by Dabbit-Chan** [MoeHero/BilibiliHelper#11]
### 问题反馈
开插件时无法自动领瓜子，显示“未绑定手机”，实际上已绑定；开插件时无法发送弹幕

### 环境信息
- 操作系统 :win10
- 插件版本 :V0.1.2.57

**Comment by MoeHero** [comment]
显示未绑定手机可以刷新页面试试看 下个版本会尝试修复
无法发送弹幕我觉得不是插件的问题 插件没有修改弹幕部分

**Comment by MoeHero** [comment]
好像未绑定手机也是因为b站炸了

**Comment by Dabbit-Chan** [comment]
感谢了
