### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by ding0000** [MoeHero/BilibiliHelper#14]
在不同浏览器安装时会直接闪退或显示程序包无效

系统 Windows10
版本 V0.1.3.58

**Comment by MoeHero** [comment]
具体原因未知 不过内核60以上的就没问题 可能谷歌改了什么东西
国内用户推荐QQ浏览器10

**Comment by ding0000** [comment]
chrome qq 搜狗 360均已使用，并没有安装成功。。
360显示程序包无效 qq浏览器安装没反应 搜狗浏览器直接闪退 Chrome显示无法添加

**Comment by xxxxuanran** [comment]
Chrome不会显示无法添加的，而是提示程序包无效。
检查你安装的chrome？

**Comment by MoeHero** [comment]
360不推荐 qq浏览器请更新10 去官网下载 搜狗可能不支持谷歌插件 chrome请去官方应用商店安装

**Comment by ding0000** [comment]
下载qq浏览器10已解决问题！！感恩~！
