### ISSUE TITLE
活動抽獎又需手動了 12.15

### ISSUE THREAD

**Issue by mpypipira** [MoeHero/BilibiliHelper#16]
### 问题反馈
12.15下午後似乎又出現上個版本問題，小電視能自動抽但活動需要手動執行。
可能是B站版本更新了，再麻煩大老調整升級版本。
謝謝大老讓我從抽獎手抽筋中解救出來。

### 环境信息
- Windows10，7各一
- CHROME
- V1.3.58

### 重现步骤/解决方案
2017.12.15 1930發現活動抽獎未抽取  需手動

**Comment by mpypipira** [comment]
有少數幾個直播間是活動抽依舊有效  但多數是需手動
大概30次裡有一個是有效  其他活動抽是需要手動的

**Comment by gskter** [comment]
金瓜子礼物的火力全开可以触发抽奖，B站赠送的嗨翻全场礼物无法触发抽奖

**Comment by MoeHero** [comment]
b站的问题吧 可以尝试更换直播间
