### ISSUE TITLE
插件突然没有用了

### ISSUE THREAD

**Issue by liduck** [MoeHero/BilibiliHelper#18]
### 问题反馈
在您提交问题前, 请检查以下项目:
- 您在报告一个 Bug 或者提交一个 功能请求. 如果您需要一般性的帮助, 请直接和我们联系.
- 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- 如果您在报告一个 Bug 请确定它可以在最新的发行版下重现.
- 请详细说明重现问题的步骤(有屏幕截图的话就更好了).  
(提交时请将上面的内容删除)

### 环境信息
- 操作系统 (Windows/Mac OS/Linux):
- 浏览器版本 (您可以在 [菜单/帮助/关于] 下查看):
- 插件版本 (您可以在 [插件选项] 内查看):

### 重现步骤/解决方案
请具体描述
今天的礼物数量挂了一天没有变化，重启插件几次也没有用。

**Comment by MoeHero** [comment]
检查一下设置 都开启了么
然后再去直播间页面按f12切换到console查看输出是否正常

**Comment by liduck** [comment]
emmmmm...有两个error
![default](https://user-images.githubusercontent.com/34301737/34072706-43cbee78-e2c7-11e7-97fa-28e6ba721d58.PNG)

**Comment by MoeHero** [comment]
error不是我的问题
请截图1652293直播间的console

**Comment by ddok520** [comment]
要在短号（3位数或以下）的房间才能抽火力全开，其他房间只能抽小电视

**Comment by li19910529** [comment]
这个插件怎么用？哪个文件放入浏览器的插件栏里啊？

**Comment by liduck** [comment]
换到短号就可以了，不过不知道为什么我以前在长号直播间挂也可以

**Comment by MoeHero** [comment]
问题还有吗？不回复的话关闭这个Issue了
