### ISSUE TITLE
特殊直播间里运行异常

### ISSUE THREAD

**Issue by bysdxt** [MoeHero/BilibiliHelper#19]
### 环境信息
- 操作系统 (Windows/Mac OS/Linux): Win10x64 1703(15063.726)
- 浏览器版本 (您可以在 [菜单/帮助/关于] 下查看): Chrome 版本 63.0.3239.108（正式版本） （64 位）
- 插件版本 (您可以在 [插件选项] 内查看): V0.1.3.58

### 重现步骤/解决方案
其他主播间都运行良好，就 https://live.bilibili.com/14047 这个直播间里有问题。
例如今天瓜子都领完了，正常直播间里瓜子那会显示领取完毕，但 14047 那是显示 已启用。
还有就是在 14047 里点到其他抽奖直播间里也不会自动抽奖（其他直播间不会，很正常）。

**Comment by mpypipira** [comment]
其它直播間都正常嗎
我現在所有房間只要是活動抽獎都要手動
已經電腦重啟插件重裝過了  還是只有自動抽小電視  活動完全無效

顯示已啟用我猜應該是因為不是主控的頁面(第一個開的B站直播間)  領瓜子是靠主控頁計算的
全關掉重開一個就會開始計時領瓜子了(個人經驗)  領完前主控頁不要關掉就行了

**Comment by mpypipira** [comment]
抽獎後出來是這個
The SSL certificate used to load resources from https://i0.hdslb.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
message.bilibili.com/api/notify/query.notify.count.do?captcha=fba1dec03cd54bdb50c0645987c21a8c&type=jsonp&ts=1513501216243&callback=cb1513501216243:1 Uncaught SyntaxError: Unexpected token :
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.164] BilibiliHelper V0.1.3.58
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.182] 自动签到: 已启用
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.184] 自动领瓜子: 已启用
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.186] 自动小电视: 已启用
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.187] 活动抽奖: 已启用
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.286] 自动领瓜子: 领取完毕
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Info [2017-12-17 17:00:17.290] 自动签到: 今日已签到
918360:1 The SSL certificate used to load resources from https://bh.moehero.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
message.bilibili.com/api/notify/query.notify.count.do?captcha=fba1dec03cd54bdb50c0645987c21a8c&type=jsonp&ts=1513501275910&callback=cb1513501275910:1 Uncaught SyntaxError: Unexpected token :
message.bilibili.com/api/notify/query.notify.count.do?captcha=fba1dec03cd54bdb50c0645987c21a8c&type=jsonp&ts=1513501335910&callback=cb1513501335910:1 Uncaught SyntaxError: Unexpected token :
message.bilibili.com/api/notify/query.notify.count.do?captcha=fba1dec03cd54bdb50c0645987c21a8c&type=jsonp&ts=1513501395910&callback=cb1513501395910:1 Uncaught SyntaxError: Unexpected token :
message.bilibili.com/api/notify/query.notify.count.do?captcha=fba1dec03cd54bdb50c0645987c21a8c&type=jsonp&ts=1513501455909&callback=cb1513501455909:1 Uncaught SyntaxError: Unexpected token :
/C:/Users/user/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ojfogapglcjncgaeniboodgjnpkdimfi/0.1.3.58_0/live.min.js:1 Object
message.bilibili.com/api/notify/query.notify.count.do?captcha=fba1dec03cd54bdb50c0645987c21a8c&type=jsonp&ts=1513501515968&callback=cb1513501515968:1 Uncaught SyntaxError: Unexpected token :

**Comment by mpypipira** [comment]
我換到4號直播間掛  好像可以了

**Comment by MoeHero** [comment]
哪个直播间显示领取完毕就是那个直播间再领取 显示已启用是只已在其他直播间启用
只有一个直播间能抽奖
