### ISSUE TITLE
在我这火力全开的礼物无法领取

### ISSUE THREAD

**Issue by iTryIt** [MoeHero/BilibiliHelper#23]
目前只能自动领小电视活动，无法领火力全开活动，目前是这样的么？

**Comment by WincerChan** [comment]
我用 Chrome 也另不了，但是室友用的是 Edge 转制版，可以领，很奇怪

**Comment by MoeHero** [comment]
f12 截图console看看

**Comment by MoeHero** [comment]
不回复我就关闭这个issue了哦

**Comment by iTryIt** [comment]
referer的问题，我自己写了个修复包搞定了
