### ISSUE TITLE
参加新春抽奖一直失败

### ISSUE THREAD

**Issue by JINxo-geek** [MoeHero/BilibiliHelper#24]
,,

**Comment by JINxo-geek** [comment]
快更新....

**Comment by JINxo-geek** [comment]
偶尔在某些房间的时候又可以了,难度是请求被服务器屏蔽了?

**Comment by MoeHero** [comment]
按F12 切换到console截图

**Comment by mirrorlim** [comment]
我的也是


![default](https://user-images.githubusercontent.com/35588254/35134607-58ae8390-fd12-11e7-8e1d-2d652f8433b3.JPG)

**Comment by MoeHero** [comment]
这个不是我这里的错误 请不要认为你能找到错误是啥 所以截图请发全 谢谢

**Comment by mirrorlim** [comment]
![default](https://user-images.githubusercontent.com/35588254/35134694-0eb2211a-fd13-11e7-9822-e5d7b033692f.JPG)
emmm
那这样是截图完整吗？

**Comment by MoeHero** [comment]
系统繁忙 我没办法 b站的问题

**Comment by MoeHero** [comment]
如果没有什么其他问题我就关闭这个issue了
