### ISSUE TITLE
活动抽奖不能在所有直播间抽奖

### ISSUE THREAD

**Issue by zzatian** [MoeHero/BilibiliHelper#26]
活动抽奖只有在很少部分直播间可以生效不能在所有直播间生效

win7，Chrome63，助手 v0.1.3.58

**Comment by MoeHero** [comment]
请描述具体错误 并提交相应的信息

**Comment by MoeHero** [comment]
如果今天内还没提交相关的信息我就只能关闭这个issue了

**Comment by zleonard415** [comment]
好像是只能在房间号是3位或是4位的才能抽奖，其他房间不能抽奖
