### ISSUE TITLE
您好~请问下载bilibilihelp.zip就可以用了吗？

### ISSUE THREAD

**Issue by star666666star** [MoeHero/BilibiliHelper#3]
您好~看到如此强大的程序很膜拜，作者棒棒哒~但是因为不懂程序，所以并不会用，不知道您是否有空解答一下呢？或者您有别的联系方式吗？谢谢~~~

**Comment by MoeHero** [comment]
如果不是chrome的话直接用crx就行 如果是chrome可能需要zip 具体请自行百度

**Comment by star666666star** [comment]
您好~已经用三种浏览器试过了，世界之窗装不上总是自动跳去360，google提示无法安装插件，360安装上了，但是却不能工作，不会自动签到领瓜子之类的。把.zip的文件都下载了，但是不知道要怎样运行哪一个呢？盼复谢谢！

**Comment by MoeHero** [comment]
直播页面瓜子数量旁边有字么？有的话就去看看设置 是不是功能没开

**Comment by star666666star** [comment]
您指的是宝箱吗？发现装了插件后，除了宝箱那个位置，别的地方都没有变化。之前宝箱会显示领瓜子的倒计时，但现在都变成了“--”这种符号。而且等很久瓜子数量也没变化。设置是打开那个插件的选项在复选框打对号就可以了吗？我打了对号也不管用，而且把那个页面关了再开，那些对号就又没了

**Comment by MoeHero** [comment]
浏览器问题 具体百度一下吧 我也不太清楚
