### ISSUE TITLE
幾時更新?????>///<

### ISSUE THREAD

**Issue by ggwanggg** [MoeHero/BilibiliHelper#31]
Bilibili更新了領寶箱算法導致自動領寶箱無效!!!
還有的是，bilibili已經偵測到插件異常的操作，並拒絕訪問，使他們不能抽小電視和領寶箱!
因此是時候更新了

**Comment by MoeHero** [comment]
在develop分支有新的測試版本 需要的話可以自己打包先用着
支持自動簽到 自動領瓜子 小電視抽獎 活動抽獎因技術原因仍在開發
領因b站封禁策略影響 在未解決被封禁問題前master分支暫時不會更新

**Comment by ggwanggg** [comment]
我有一個小建議⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄
這次小電視抽獎,活動抽獎更新,可以模擬實際操作,後台進入有抽獎的直播間,並逗留一段小時間,模擬真人抽獎。
並且可以彈出用戶提示，避免24小時掛機使用插件，避免被偵測到異常操作。只要在抽獎最頻密的時段20:00 - 01:00使用插件即可←◡←
加油支持你們開發⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄麼麼噠
