### ISSUE TITLE
直播聊天信息经常不刷新

### ISSUE THREAD

**Issue by a253208088** [MoeHero/BilibiliHelper#4]
直播聊天信息经常过一段时间就不刷新了  只剩系统信息

**Comment by MoeHero** [comment]
我认为这是b站的问题 你用的html5播放器吧？

**Comment by a253208088** [comment]
是用的HTML5  。 但我用另一个助手就从没出过这个问题

**Comment by MoeHero** [comment]
禁用插件后试试看呢？我这边测试的不管是否开启插件html5播放器就是收不到弹幕，所以我认为是b站的锅

**Comment by a253208088** [comment]
开插件一开始有弹幕   ，等一段时间我浏览其他网页在跳回来就没得了，聊天信息就只显示系统信息。
我关了插件就没的这种情况

**Comment by MoeHero** [comment]
理论上不会出现这种问题吧-.-
提供一下插件版本及浏览器、操作系统的信息

**Comment by a253208088** [comment]
插件0.0.21.45
chrome版本 59.0.3071.86（正式版本） （64 位）
win10版本1703

**Comment by MoeHero** [comment]
唔 我这边测试的就是不管开不开插件 html5始终收不到弹幕
你从群里找我一下吧
