### ISSUE TITLE
我的chrome无法在线安装，会显示安装失败

### ISSUE THREAD

**Issue by lwdc5440** [MoeHero/BilibiliHelper#5]
### 问题反馈
在您提交问题前, 请检查以下项目:
- 您在报告一个 Bug 或者提交一个 功能请求. 如果您需要一般性的帮助, 请直接和我们联系.
- 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- 如果您在报告一个 Bug 请确定它可以在最新的发行版下重现.
- 请详细说明重现问题的步骤(有屏幕截图的话就更好了).  
(提交时请将上面的内容删除)

### 环境信息
- 操作系统 (Windows/Mac OS/Linux):
- 浏览器版本 (您可以在 [菜单/帮助/关于] 下查看):
- 插件版本 (您可以在 [插件选项] 内查看):

### 重现步骤/解决方案
请具体描述

**Comment by MoeHero** [comment]
点击在线安装直接就显示失败吗？
